import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Use Google, not local, for Inter
import "./globals.css";
import AuthProvider from './components/auth-provider';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth'
  import Navigation from './components/Navigation';
const inter = Inter({
  variable: "--font-inter", // Recommended variable naming format
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <AuthProvider session={session}
                    <Navigation />>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
