import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Use Google, not local, for Inter
import "./globals.css";

const inter = Inter({
  variable: "--font-inter", // Recommended variable naming format
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
