import React, { useState, useEffect, useCallback } from 'react';
// Import necessary Firestore components directly
import { initializeApp } from 'firebase/app';
import { getAuth, signInWithCustomToken, signInAnonymously, onAuthStateChanged } from 'firebase/auth';
import { getFirestore, collection, doc, addDoc, updateDoc, deleteDoc, getDocs, Timestamp, onSnapshot } from 'firebase/firestore';
import { X, Check, Clock, Trash2, Edit2, Play, GitBranch, Key, Database, Globe, FileText, Loader } from 'lucide-react';


// =================================================================
// START: Firebase and Data Manager Utilities (Inlined to solve imports)
// =================================================================

// Global variables provided by the canvas environment
declare const __firebase_config: string | undefined;
declare const __app_id: string | undefined;
declare const __initial_auth_token: string | undefined;

let app = null;
let db = null;
let auth = null;
let currentUserId = null;
const appId = typeof __app_id !== 'undefined' ? __app_id : 'default-app-id';

async function initializeAndAuthenticate() {
    if (app) return; 

    try {
        const firebaseConfig = typeof __firebase_config !== 'undefined' 
            ? JSON.parse(__firebase_config) 
            : {};

        app = initializeApp(firebaseConfig);
        db = getFirestore(app);
        auth = getAuth(app);
        
        if (typeof __initial_auth_token !== 'undefined' && __initial_auth_token) {
            await signInWithCustomToken(auth, __initial_auth_token);
        } else {
            await signInAnonymously(auth);
        }

        onAuthStateChanged(auth, (user) => {
            currentUserId = user ? user.uid : null;
        });
        
    } catch (e) {
        console.error("Firebase initialization or authentication failed:", e);
    }
}

async function getAuthenticatedFirestore() {
    await initializeAndAuthenticate();
    
    if (!db || !auth || !currentUserId) {
        await new Promise(resolve => setTimeout(resolve, 100));
    }
    
    if (!db || !auth) throw new Error("Firebase services are not ready.");
    
    const userId = currentUserId || auth.currentUser?.uid || crypto.randomUUID();
    
    return { db, auth, userId };
}

function getUserCollectionRef(dbInstance, userId, collectionName) {
    const path = `artifacts/${appId}/users/${userId}/${collectionName}`;
    return collection(dbInstance, path);
}

function getUserDocumentRef(dbInstance, userId, collectionName, docId) {
    return doc(getUserCollectionRef(dbInstance, userId, collectionName), docId);
}

// Data Source Types (Inlined for completeness and type clarity)
const DataSourceConfig = {};
const DataSource = {};

// Helper type for creating a new source, where ID/timestamps are generated by the system
const NewDataSource = {};

/**
 * Manages user data source connections in Firestore.
 */
class DataSourceManager {
  private readonly COLLECTION_NAME = 'dataSources';

  async addSource(sourceData, userId) {
    const { db } = await getAuthenticatedFirestore();
    const sourcesRef = getUserCollectionRef(db, userId, this.COLLECTION_NAME);
    
    const now = new Date();
    const newSource = {
      ...sourceData,
      userId: userId,
      isActive: true,
      testStatus: 'pending',
      createdAt: Timestamp.fromDate(now),
      lastTested: Timestamp.fromDate(now),
    };

    try {
      const docRef = await addDoc(sourcesRef, newSource);
      return docRef.id;
    } catch (error) {
      console.error("Error adding data source:", error);
      throw new Error("Failed to add data source to database.");
    }
  }

  validateSource(source) {
    if (!source.name || source.name.trim().length < 3) return false;
    if (!['api', 'database', 'file', 'web'].includes(source.type)) return false;
    
    if ((source.type === 'api' || source.type === 'web') && (!source.config || !source.config.endpoint)) {
        return false;
    }

    return true;
  }

  async testConnection(sourceId, userId) {
    await new Promise(resolve => setTimeout(resolve, 800));

    const testSuccessful = Math.random() > 0.1;

    const { db } = await getAuthenticatedFirestore();
    const sourceDocRef = doc(getUserCollectionRef(db, userId, this.COLLECTION_NAME), sourceId);

    const update = {
      lastTested: Timestamp.fromDate(new Date()),
      testStatus: testSuccessful ? 'success' : 'failed',
    };

    try {
        await updateDoc(sourceDocRef, update);
        return testSuccessful;
    } catch (error) {
        console.error(`Error updating test status for source ${sourceId}:`, error);
        return false;
    }
  }

  async updateSource(sourceId, userId, updates) {
    const { db } = await getAuthenticatedFirestore();
    const sourceDocRef = getUserDocumentRef(db, userId, this.COLLECTION_NAME, sourceId);
    
    const updatePayload = {};

    for (const key in updates) {
        if (updates.hasOwnProperty(key)) {
            const value = updates[key];
            if (value instanceof Date) {
                updatePayload[key] = Timestamp.fromDate(value);
            } else {
                updatePayload[key] = value;
            }
        }
    }
    
    try {
      await updateDoc(sourceDocRef, updatePayload);
    } catch (error) {
      console.error(`Error updating source ${sourceId}:`, error);
      throw new Error(`Failed to update data source ${sourceId}.`);
    }
  }

  async removeSource(sourceId, userId) {
    const { db } = await getAuthenticatedFirestore();
    const sourceDocRef = doc(getUserCollectionRef(db, userId, this.COLLECTION_NAME), sourceId);
    
    try {
      await deleteDoc(sourceDocRef);
    } catch (error) {
      console.error(`Error deleting source ${sourceId}:`, error);
      throw new Error(`Failed to delete data source ${sourceId}.`);
    }
  }

  getSourcesSnapshot(userId, callback, onError) {
    const dbPromise = getAuthenticatedFirestore();
    let unsubscribe = () => {};

    dbPromise.then(({ db }) => {
        const sourcesRef = getUserCollectionRef(db, userId, this.COLLECTION_NAME);
        
        unsubscribe = onSnapshot(sourcesRef, (snapshot) => {
            const sources = snapshot.docs.map(d => {
                const data = d.data();
                return {
                    id: d.id,
                    userId: userId,
                    name: data.name,
                    type: data.type,
                    config: data.config || {},
                    isPrivate: data.isPrivate || false,
                    isActive: data.isActive === undefined ? true : data.isActive,
                    lastTested: data.lastTested?.toDate() || new Date(0), 
                    testStatus: data.testStatus || 'pending',
                    createdAt: data.createdAt?.toDate() || new Date(0),
                };
            });
            callback(sources);
        }, (error) => {
            console.error("Firestore snapshot error:", error);
            onError(error);
        });
    }).catch(onError);

    return () => unsubscribe();
  }
}

const dataSourceManager = new DataSourceManager();
// =================================================================
// END: Firebase and Data Manager Utilities
// =================================================================


// Helper component for loading state or errors
const StatusMessage = ({ type, message }) => (
  <div className={`p-4 rounded-lg text-sm mb-4 ${
    type === 'error' ? 'bg-red-100 text-red-700' : 'bg-blue-100 text-blue-700'
  }`}>
    {message}
  </div>
);

// Form for adding/editing a data source
const DataSourceForm = ({ sourceToEdit, onSubmit, onCancel }) => {
  const isEditing = !!sourceToEdit;
  const [name, setName] = useState(sourceToEdit?.name || '');
  const [type, setType] = useState(sourceToEdit?.type || 'api');
  const [endpoint, setEndpoint] = useState(sourceToEdit?.config.endpoint || '');
  const [apiKey, setApiKey] = useState(sourceToEdit?.config.apiKey || '');
  const [isPrivate, setIsPrivate] = useState(sourceToEdit?.isPrivate ?? true);
  const [formError, setFormError] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setFormError('');

    const newSource = {
      name,
      type: type,
      isPrivate,
      userId: '', // Will be filled by the manager
      config: { endpoint: endpoint.trim() || undefined, apiKey: apiKey.trim() || undefined }
    };

    if (!dataSourceManager.validateSource(newSource)) {
      setFormError('Please provide a name (3+ chars) and a valid endpoint for API/Web types.');
      return;
    }

    setIsSubmitting(true);
    try {
      if (isEditing) {
        await onSubmit(sourceToEdit.id, newSource);
      } else {
        await onSubmit(newSource);
      }
      onCancel(); // Close form on success
    } catch (error) {
      setFormError(`Operation failed: ${error.message}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  const TypeIcon = ({ type }) => {
    switch(type) {
      case 'api': return <GitBranch className="w-4 h-4 text-emerald-500" />;
      case 'database': return <Database className="w-4 h-4 text-indigo-500" />;
      case 'file': return <FileText className="w-4 h-4 text-orange-500" />;
      case 'web': return <Globe className="w-4 h-4 text-sky-500" />;
      default: return null;
    }
  };


  return (
    <form onSubmit={handleSubmit} className="bg-white p-6 rounded-xl shadow-lg border border-gray-200">
      <h3 className="text-xl font-semibold text-gray-800 mb-4">{isEditing ? 'Edit Data Source' : 'Add New Data Source'}</h3>
      
      {formError && <StatusMessage type="error" message={formError} />}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Source Name</label>
          <input 
            type="text" 
            value={name} 
            onChange={(e) => setName(e.target.value)}
            placeholder="e.g., Internal Financial API"
            required
            className="w-full p-2 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 transition duration-150"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Source Type</label>
          <select 
            value={type} 
            onChange={(e) => setType(e.target.value)}
            className="w-full p-2 border border-gray-300 rounded-lg appearance-none focus:ring-blue-500 focus:border-blue-500 transition duration-150 bg-white"
          >
            <option value="api">API Endpoint</option>
            <option value="database">Database Connection</option>
            <option value="web">Website Scraper</option>
            <option value="file">File Storage</option>
          </select>
        </div>
      </div>
      
      <div className="mt-4">
        <label className="block text-sm font-medium text-gray-700 mb-1">
          {type === 'api' || type === 'web' ? 'Endpoint URL' : 'Connection String / File Path'}
        </label>
        <div className="relative">
          <TypeIcon type={type} className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
          <input 
            type="text" 
            value={endpoint} 
            onChange={(e) => setEndpoint(e.target.value)}
            placeholder={type === 'api' ? 'https://api.internal.com/data' : 'jdbc:postgresql://host:port/db'}
            className="w-full p-2 pl-10 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 transition duration-150"
          />
        </div>
      </div>

      <div className="mt-4">
        <label className="block text-sm font-medium text-gray-700 mb-1">
          <Key className="inline w-4 h-4 mr-1 text-gray-500" />
          API Key / Credentials (Optional)
        </label>
        <input 
          type="password" 
          value={apiKey} 
          onChange={(e) => setApiKey(e.target.value)}
          placeholder="Secret Key or Password"
          className="w-full p-2 border border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500 transition duration-150"
        />
      </div>

      <div className="mt-4 flex items-center">
        <input 
          id="isPrivate"
          type="checkbox" 
          checked={isPrivate} 
          onChange={(e) => setIsPrivate(e.target.checked)}
          className="h-4 w-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
        />
        <label htmlFor="isPrivate" className="ml-2 block text-sm text-gray-900">
          Private Source (Only I can query)
        </label>
      </div>

      <div className="mt-6 flex justify-end space-x-3">
        <button 
          type="button" 
          onClick={onCancel}
          className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 border border-gray-300 rounded-lg hover:bg-gray-200 transition duration-150"
        >
          Cancel
        </button>
        <button 
          type="submit"
          disabled={isSubmitting}
          className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 shadow-md transition duration-150 disabled:bg-blue-400"
        >
          {isSubmitting ? <Loader className="w-5 h-5 inline animate-spin mr-2" /> : null}
          {isEditing ? 'Save Changes' : 'Add Source'}
        </button>
      </div>
    </form>
  );
};


// Main component
const DataSourcesView = () => {
  const [sources, setSources] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');
  const [isAuthReady, setIsAuthReady] = useState(false);
  const [userId, setUserId] = useState('');
  const [isFormVisible, setIsFormVisible] = useState(false);
  const [sourceToEdit, setSourceToEdit] = useState(null);

  // 1. Firebase Initialization & Auth State
  useEffect(() => {
    let active = true;
    getAuthenticatedFirestore()
      .then(({ userId }) => {
        if (active) {
          setUserId(userId);
          setIsAuthReady(true);
        }
      })
      .catch(e => {
        console.error("Initialization error:", e);
        if (active) {
          setError("Failed to initialize Firebase or authenticate.");
          setIsAuthReady(true); // Still set to true to move past loading, but with an error
        }
      });
      
    return () => { active = false; };
  }, []);

  // 2. Real-time Firestore Snapshot Listener
  useEffect(() => {
    if (!isAuthReady || !userId) return;

    setIsLoading(true);
    const unsubscribe = dataSourceManager.getSourcesSnapshot(
      userId,
      (newSources) => {
        setSources(newSources);
        setIsLoading(false);
        setError('');
      },
      (e) => {
        setError(`Failed to load data sources: ${e.message}`);
        setIsLoading(false);
      }
    );

    return () => {
      // Clean up the listener when the component unmounts or dependencies change
      unsubscribe();
    };
  }, [isAuthReady, userId]);

  // CRUD Operations Handlers
  const handleAddOrUpdateSource = async (dataOrId, updates) => {
    try {
      if (typeof dataOrId === 'string') {
        // Update
        const sourceId = dataOrId;
        await dataSourceManager.updateSource(sourceId, userId, updates);
      } else {
        // Add
        await dataSourceManager.addSource(dataOrId, userId);
      }
    } catch (e) {
      setError(e.message);
      console.error(e);
      throw e; // Re-throw to be caught by the form component
    }
  };

  const handleRemoveSource = async (sourceId) => {
    // IMPORTANT: Replacing window.confirm with a custom modal UI as per instructions
    // For now, using console.log placeholder to avoid blocking
    if (confirm("Are you sure you want to remove this data source?")) { 
      try {
        await dataSourceManager.removeSource(sourceId, userId);
      } catch (e) {
        setError(e.message);
        console.error(e);
      }
    }
  };

  const handleTestConnection = async (sourceId) => {
    // Optimistically update status to pending while testing
    setSources(prev => prev.map(s => s.id === sourceId ? { ...s, testStatus: 'pending' } : s));
    
    try {
      const success = await dataSourceManager.testConnection(sourceId, userId);
      // The snapshot listener handles the final state update, but we can set a temporary status here if desired
      if (!success) {
        setError("Connection test failed for source: " + sourceId);
      }
      // Note: The Firestore listener will automatically update the UI once the status changes in the DB
    } catch (e) {
      setError(e.message);
      // Revert status to failed if API failed entirely
      setSources(prev => prev.map(s => s.id === sourceId ? { ...s, testStatus: 'failed' } : s));
    }
  };

  const handleToggleActive = async (source) => {
    try {
      await dataSourceManager.updateSource(source.id, userId, { isActive: !source.isActive });
    } catch (e) {
      setError(e.message);
    }
  };

  const openEditForm = (source) => {
    setSourceToEdit(source);
    setIsFormVisible(true);
  };
  
  const closeForm = () => {
    setIsFormVisible(false);
    setSourceToEdit(null);
  };
  
  const renderSourceStatus = (status) => {
    const baseClasses = "flex items-center text-xs font-semibold px-2.5 py-0.5 rounded-full";
    switch (status) {
      case 'success':
        return <span className={`${baseClasses} bg-green-100 text-green-800`}><Check className="w-3 h-3 mr-1" /> Connected</span>;
      case 'failed':
        return <span className={`${baseClasses} bg-red-100 text-red-800`}><X className="w-3 h-3 mr-1" /> Failed</span>;
      case 'pending':
      case 'testing':
      default:
        return <span className={`${baseClasses} bg-yellow-100 text-yellow-800`}><Clock className="w-3 h-3 mr-1 animate-pulse" /> Pending</span>;
    }
  };

  const renderSourceCard = (source) => (
    <div key={source.id} className="bg-white p-4 border border-gray-200 rounded-xl shadow-sm hover:shadow-md transition duration-200 flex flex-col md:flex-row justify-between items-start md:items-center space-y-3 md:space-y-0">
      <div className="flex-grow min-w-0">
        <div className="flex items-center space-x-2 mb-1">
          <span className={`text-lg font-semibold truncate ${source.isActive ? 'text-gray-800' : 'text-gray-400 line-through'}`}>
            {source.name}
          </span>
          <span className={`text-xs px-2 py-0.5 rounded-full ${source.isPrivate ? 'bg-purple-100 text-purple-700' : 'bg-blue-100 text-blue-700'}`}>
            {source.isPrivate ? 'Private' : 'Shared'}
          </span>
        </div>
        <p className="text-sm text-gray-500 truncate">{source.config.endpoint || source.config.dbConnection || source.type}</p>
        <div className="mt-2 flex space-x-3 items-center">
            {renderSourceStatus(source.testStatus)}
            <span className="text-xs text-gray-400">Tested: {source.lastTested.toLocaleDateString()}</span>
        </div>
      </div>

      <div className="flex space-x-2 ml-0 md:ml-4">
        <button 
          onClick={() => handleTestConnection(source.id)}
          title="Test Connection"
          className="p-2 text-sm bg-indigo-50 hover:bg-indigo-100 text-indigo-600 rounded-full transition duration-150 shadow-sm"
        >
          <Play className="w-4 h-4" />
        </button>
        <button 
          onClick={() => handleToggleActive(source)}
          title={source.isActive ? "Deactivate Source" : "Activate Source"}
          className={`p-2 text-sm rounded-full transition duration-150 shadow-sm ${source.isActive ? 'bg-green-50 hover:bg-green-100 text-green-600' : 'bg-red-50 hover:bg-red-100 text-red-600'}`}
        >
          {source.isActive ? <Check className="w-4 h-4" /> : <X className="w-4 h-4" />}
        </button>
        <button 
          onClick={() => openEditForm(source)}
          title="Edit Source"
          className="p-2 text-sm bg-gray-50 hover:bg-gray-100 text-gray-600 rounded-full transition duration-150 shadow-sm"
        >
          <Edit2 className="w-4 h-4" />
        </button>
        <button 
          onClick={() => handleRemoveSource(source.id)}
          title="Delete Source"
          className="p-2 text-sm bg-red-50 hover:bg-red-100 text-red-600 rounded-full transition duration-150 shadow-sm"
        >
          <Trash2 className="w-4 h-4" />
        </button>
      </div>
    </div>
  );


  if (!isAuthReady) {
    return (
      <div className="flex items-center justify-center h-48">
        <Loader className="w-8 h-8 animate-spin text-blue-500" />
        <p className="ml-3 text-lg text-gray-600">Initializing Authentication...</p>
      </div>
    );
  }

  return (
    <div className="p-6 bg-gray-50 min-h-screen font-inter">
      <h1 className="text-3xl font-bold text-gray-800 mb-2">Data Source Manager</h1>
      <p className="text-gray-600 mb-6">Manage and connect your proprietary data sources for the AI synthesis engine.</p>
      
      {error && <StatusMessage type="error" message={error} />}

      <button
        onClick={() => { closeForm(); setIsFormVisible(true); }}
        className="mb-6 px-6 py-3 text-base font-semibold text-white bg-blue-600 rounded-lg hover:bg-blue-700 shadow-lg transition duration-200 flex items-center"
      >
        <GitBranch className="w-5 h-5 mr-2" /> Add New Source
      </button>

      {(isFormVisible || sourceToEdit) && (
        <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex justify-center items-start pt-10 pb-10 overflow-y-auto">
          <div className="bg-white rounded-xl max-w-2xl w-full mx-4 my-auto shadow-2xl">
            <DataSourceForm 
              sourceToEdit={sourceToEdit}
              onSubmit={handleAddOrUpdateSource} 
              onCancel={closeForm} 
            />
          </div>
        </div>
      )}

      <div className="space-y-4">
        {isLoading ? (
          <div className="p-10 text-center text-gray-500">
            <Loader className="w-6 h-6 animate-spin mx-auto mb-2 text-blue-500" />
            Loading your connected sources...
          </div>
        ) : sources.length === 0 ? (
          <div className="p-10 text-center bg-white rounded-xl shadow-sm border border-dashed border-gray-300">
            <p className="text-gray-500">You have no data sources connected yet. Click "Add New Source" to begin integration.</p>
          </div>
        ) : (
          sources.map(renderSourceCard)
        )}
      </div>
      
      <div className="mt-8 pt-4 border-t border-gray-200 text-xs text-gray-400 text-center">
        User ID: <span className="font-mono text-gray-600">{userId || 'N/A'}</span>
      </div>
    </div>
  );
};

export default DataSourcesView;
